import { Link, useLocation, useNavigate } from "@tanstack/react-router";
import { Bell, Heart, Home, LayoutGrid, LogIn, Medal, Radio, Search, Shield, Swords, Trophy, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { playUiSound } from "@/lib/sounds";

const links = [["Home", "/", Home], ["Leagues", "/leagues", Trophy], ["Fixtures", "/fixtures", Radio], ["Results", "/results", Medal], ["Teams", "/teams", Shield], ["Players", "/players", Users], ["Transfers", "/transfers", Swords], ["Favourites", "/favourites", Heart], ["Notifications", "/notifications", Bell]] as const;

export function NovaSidebar({ mobileOpen, onClose }: { mobileOpen?: boolean; onClose?: () => void }) {
  const location = useLocation(); const navigate = useNavigate(); const [role, setRole] = useState<string | null>(null);
  useEffect(() => { let mounted = true; supabase.auth.getUser().then(({ data }) => { if (mounted) setRole((data.user?.app_metadata?.role ?? data.user?.user_metadata?.role) as string | null); }); return () => { mounted = false; }; }, []);
  return <>{mobileOpen && <button aria-label="Close navigation" onClick={onClose} className="fixed inset-0 z-40 bg-black/70 lg:hidden" />}<aside className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r border-border bg-sidebar transition-transform duration-200 lg:static lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-20 items-center justify-between border-b border-border px-6"><Link to="/" className="flex items-center gap-3 text-foreground"><img src="/nova-icon.jpeg" alt="NOVA" className="size-8 rounded-lg object-cover" /><span className="font-black tracking-[0.24em]">NOVA</span></Link><button onClick={onClose} aria-label="Close navigation" className="rounded-md p-2 lg:hidden"><X className="size-5" /></button></div><nav className="flex-1 space-y-1 px-3 py-5">{links.map(([label, to, Icon]) => <Link key={label} to={to as any} onClick={() => { onClose?.(); playUiSound(); }} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium ${location.pathname === to ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-white/10 hover:text-foreground"}`}><Icon className="size-4" />{label}</Link>)}{role === "admin" && <Link to={"/admin" as any} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium ${location.pathname === "/admin" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-white/10 hover:text-foreground"}`}><Shield className="size-4" />Admin</Link>}</nav><div className="border-t border-border p-3"><button onClick={async () => { playUiSound(); await supabase.auth.signOut(); void navigate({ to: "/auth" as any }); }} className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-white/10 hover:text-foreground"><LogIn className="size-4" />Sign out</button></div></aside></>;
}

export function NovaHeader({ onMenu }: { onMenu: () => void }) { return <header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-border bg-sidebar/95 px-5 backdrop-blur lg:px-8"><button aria-label="Open navigation" onClick={onMenu} className="rounded-md p-2 lg:hidden"><LayoutGrid className="size-5" /></button><div className="relative hidden w-full max-w-md lg:block"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><input aria-label="Search teams, players, leagues or matches" placeholder="Search teams, players, leagues..." className="h-10 w-full rounded-lg border border-border bg-card pl-10 pr-4 text-sm outline-none placeholder:text-muted-foreground focus:border-foreground" /></div><div className="ml-auto flex items-center gap-4"><button aria-label="Notifications" className="rounded-md p-2 text-muted-foreground hover:bg-white/10 hover:text-foreground"><Bell className="size-5" /></button><img src="/nova-icon.jpeg" alt="NOVA" className="size-9 rounded-lg border border-border object-cover" /></div></header>; }
