/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as LeaguesLeagueIdRouteImport } from './routes/leagues/$leagueId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LeaguesLeagueIdRoute = LeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => LeaguesRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favourites': typeof FavouritesRoute
  '/fixtures': typeof FixturesRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/players': typeof PlayersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favourites': typeof FavouritesRoute
  '/fixtures': typeof FixturesRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/players': typeof PlayersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favourites': typeof FavouritesRoute
  '/fixtures': typeof FixturesRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/players': typeof PlayersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/leagues/$leagueId': typeof LeaguesLeagueIdRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/favourites'
    | '/fixtures'
    | '/leagues'
    | '/notifications'
    | '/players'
    | '/profile'
    | '/results'
    | '/teams'
    | '/transfers'
    | '/dashboard'
    | '/leagues/$leagueId'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/favourites'
    | '/fixtures'
    | '/leagues'
    | '/notifications'
    | '/players'
    | '/profile'
    | '/results'
    | '/teams'
    | '/transfers'
    | '/dashboard'
    | '/leagues/$leagueId'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/favourites'
    | '/fixtures'
    | '/leagues'
    | '/notifications'
    | '/players'
    | '/profile'
    | '/results'
    | '/teams'
    | '/transfers'
    | '/_authenticated/dashboard'
    | '/leagues/$leagueId'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FavouritesRoute: typeof FavouritesRoute
  FixturesRoute: typeof FixturesRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TransfersRoute: typeof TransfersRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/leagues/$leagueId': {
      id: '/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LeaguesLeagueIdRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LeaguesRouteChildren {
  LeaguesLeagueIdRoute: typeof LeaguesLeagueIdRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesLeagueIdRoute: LeaguesLeagueIdRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FavouritesRoute: FavouritesRoute,
  FixturesRoute: FixturesRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PlayersRoute: PlayersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TransfersRoute: TransfersRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
